version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "vitest"
          - "tsup"
          - "tsx"
          - "typescript"
          - "@biomejs/biome"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"